import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

  banners: [
    {
      name: 'Banner 1',
      image: '/images/banner-1.jpg',
    },
    {
      name: 'Banner 2',
      image: '/images/banner-2.jpg',
    },
  ],

    products: [
        {
          name: 'Free Shirt',
          slug: 'free-shirt',
          category: 'Shirts',
          image: '/images/shirt1.jpg',
          price: 70,
          brand: 'Nike',
          rating: 4.5,
          numReviews: 8,
          countInStock: 20,
          description: 'A slim cut t-shirt will emphasise the shoulders, but a straighter cut will have a more even look. Round – a round body shape has a large bust and a bigger midsection – a classic cut will give the most relaxed, flattering look.',
          // isFeatured: true,
          // banner: '/images/banner1.jpg',
        },
        {
          name: 'Fit Shirt',
          slug: 'fit-shirt',
          category: 'Shirts',
          image: '/images/shirt2.jpg',
          price: 80,
          brand: 'Adidas',
          rating: 3.2,
          numReviews: 10,
          countInStock: 20,
          description: 'A slim cut t-shirt will emphasise the shoulders, but a straighter cut will have a more even look. Round – a round body shape has a large bust and a bigger midsection – a classic cut will give the most relaxed, flattering look.',
          // isFeatured: true,
          // banner: '/images/banner2.jpg',
        },
        {
          name: 'Slim Shirt',
          slug: 'slim-shirt',
          category: 'Shirts',
          image: '/images/shirt3.jpg',
          price: 90,
          brand: 'Raymond',
          rating: 4.5,
          numReviews: 3,
          countInStock: 20,
          description: 'A slim cut t-shirt will emphasise the shoulders, but a straighter cut will have a more even look. Round – a round body shape has a large bust and a bigger midsection – a classic cut will give the most relaxed, flattering look.',
        },
        {
          name: 'Golf Pants',
          slug: 'golf-pants',
          category: 'Pants',
          image: '/images/pants1.jpg',
          price: 90,
          brand: 'Oliver',
          rating: 2.9,
          numReviews: 13,
          countInStock: 20,
          description: 'Smart looking pants',
        },
        {
          name: 'Fit Pants',
          slug: 'fit-pants',
          category: 'Pants',
          image: '/images/pants2.jpg',
          price: 95,
          brand: 'Zara',
          rating: 3.5,
          numReviews: 7,
          countInStock: 20,
          description: 'A popular pants',
        },
        {
          name: 'Classic Pants',
          slug: 'classic-pants',
          category: 'Pants',
          image: '/images/pants3.jpg',
          price: 75,
          brand: 'Casely',
          rating: 2.4,
          numReviews: 14,
          countInStock: 20,
          description: 'A popular pants',
        },
      ],
}

export default data